export const projects = [
  {
    title: 'ShowOff',
    description: "Blog-like web application that allows users to share what they wish with others in the community. This project is still on-going to which I will turn it full-stack and allow users to register and login while having access to full functionality within the application.",
      image: '/images/show-off.png',
      tags: ['React', 'CSS', 'HTML', 'Node'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/ShowOff',
    id: 0,
  },
  {
    title: 'VapurBot (AI ChatBot)',
    description: "For my fellow programmers at Vapur.io, I created a chatbot with deep learning capabilities that responded to user input about Vapur. With over 98% accuracy, the VapurBot is a well-designed machine to relay information related to Vapur.  ",
    image: '/images/vapur.png',
    tags: ['Python', 'Machine Learning', 'AI'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/VapurChatBot',
    id: 1,
  },
  {
    title: 'eSurance',
    description: "Using HTML & CSS, this project was unique in a way that made our website fully responsive, including mobile navigation! Web design was motivated by DesignCourse's HTML & CSS crash course on YouTube. eSurance is a company designed to insure this and upcoming generations of gamers that are in a rapidly growing sport. ",
      image: '/images/esurance.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'Front-End'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/eSurance',
    id: 2,
  },
  {
    title: 'CovidCounter',
    description: "This was a simple project that I thought was very hands-on with Tailwind and Vue, while also being relatable to our nation's current situation. Click the button below to learn more about the API used. ",
    image: '/images/covid.png',
    tags: ['Vue', 'Tailwind', 'API', 'Front-End'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/covidCounter',
    id: 3,
  },
  {
    title: 'Weather API Application',
    description:"This automation project was intended to use a 3rd party API via openweathermap. In doing so, I created an application that allowed the user to submit an input of a city that they wanted climate information about. In return, my application would reflect those results from the requested cities. This idea to use a weather API was gifted by Tech With Tim, none of this would've been possible without him. ",
    image: '/images/weather.png',
    tags: ['Python', 'API'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/ClimateFinder', //"CODE"
    id: 4,
  },
  {
    title: 'nVenue Microservice',
    description:"A task provided by nVenue, a newly funded company that implements machine learning and artificial intelligence to predict real-time analytics for sport micro-betting. My goal was to create a microservice that iterated over large csv files and predicted the model's prediction accuracy. ",
    image: '/images/nvenue.png',
    tags: ['Python', 'Data Processing', 'Machine Learning'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/nVenue-coding-challenge', //"CODE"
    id: 5,
  },
];
