export const projects = [
  {
    title: 'eSurance',
    description: "Using HTML & CSS, this project was unique in a way that made our website fully responsive, including mobile navigation! Web design was motivated by DesignCourse's HTML & CSS crash course on YouTube. eSurance is a company designed to insure this and upcoming generations of gamers that are in a rapidly growing sport. ",
      image: '/images/esurance.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'Front-End'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/eSurance',
    id: 0,
  },
  {
    title: 'ShowOff',
    description: "I am currently working on a full-stack project I am calling ShowOff, where users can share what they are passionate about on a blog-like application. I am always working, so it should be posted here soon! In the meantime, click the button below to view my github repository.",
      image: '/images/work.jpg',
      tags: ['', ''],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC?tab=repositories',
    id: 1,
  },
  {
    title: 'VapurBot (AI ChatBot)',
    description: "For my fellow programmers at Vapur.io, I created a chatbot with deep learning capabilities that responded to user input about Vapur. With over 98% accuracy, the VapurBot is a well-designed machine to relay information related to Vapur.  ",
    image: '/images/vapur.png',
    tags: ['Python', 'Machine Learning', 'AI'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/VapurChatBot',
    id: 2,
  },
  {
    title: 'CovidCounter',
    description: "This was a simple project that I thought was very hands-on with Tailwind and Vue, while also being relatable to our nation's current situation. Click the button below to learn more about the API used. ",
    image: '/images/covid.png',
    tags: ['Vue', 'Tailwind', 'API', 'Front-End'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/covidCounter',
    id: 3,
  },
  {
    title: 'Weather API Application',
    description:"This automation project was intended to use a 3rd party API via openweathermap. In doing so, I created an application that allowed the user to submit an input of a city that they wanted climate information about. In return, my application would reflect those results from the requested cities. This idea to use a weather API was gifted by Tech With Tim, none of this would've been possible without him. ",
    image: '/images/weather.png',
    tags: ['Python', 'API'],
    source: 'https://google.com',
    visit: 'https://github.com/JayvenC/ClimateFinder', //"CODE"
    id: 4,
  },
];
